const fs = require('fs');
const path = require('path');

const categories = {
  '한국사':   'data/history.json',
  '과학':     'data/science.json',
  '지리':     'data/geography.json',
  '일반상식': 'data/general.json',
};

const result = {};
for (const [key, file] of Object.entries(categories)) {
  const filePath = path.join(__dirname, file);
  result[key] = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  console.log(`  읽음: ${file} (${result[key].length}문제)`);
}

const output = `/* Auto-generated by build-data.js — do not edit manually */\nwindow.__QUIZ_DATA__ = ${JSON.stringify(result)};\n`;
const outPath = path.join(__dirname, 'data', 'questions.js');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`\n✅ data/questions.js 생성 완료 (총 ${Object.values(result).reduce((s, a) => s + a.length, 0)}문제)`);
